import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AccountField, AccountPage, Notice, ui } from '@/components/account/AccountUI';
import { AppButton } from '@/components/AppButton';
import { MotionPressable } from '@/components/Motion';
import { useFarm } from '@/contexts/FarmContext';
import { useLanguage } from '@/contexts/LanguageContext';
import { colors, radius, spacing, typography } from '@/constants/theme';
import { CustomerServiceError } from '@/services/apiClient';
import { farmService } from '@/services/farm';
import type { AreaUnit, FarmType } from '@/types/farm';

const types:Array<{value:FarmType;ar:string;en:string}>=[{value:'farm',ar:'مزرعة',en:'Farm'},{value:'greenhouse',ar:'بيت محمي',en:'Greenhouse'},{value:'home_garden',ar:'حديقة منزلية',en:'Home garden'},{value:'rooftop',ar:'زراعة سطح',en:'Rooftop'},{value:'project',ar:'مشروع زراعي',en:'Project'},{value:'other',ar:'أخرى',en:'Other'}];
export default function FarmForm(){
  const {language,isRTL}=useLanguage(),{refresh}=useFarm(),ar=language==='ar';
  const [name,setName]=useState(''),[type,setType]=useState<FarmType>('farm'),[emirate,setEmirate]=useState(''),[region,setRegion]=useState(''),[area,setArea]=useState(''),[unit,setUnit]=useState<AreaUnit>('m2'),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const save=async()=>{if(!name.trim()){setError(ar?'اكتب اسم المزرعة.':'Enter a farm name.');return;}setBusy(true);setError('');try{const farm=await farmService.createFarm({name:name.trim(),type,emirate,region,area:area?Number(area):undefined,areaUnit:area?unit:undefined,notes});await refresh();router.replace({pathname:'/my-farm/[farmId]',params:{farmId:farm.id,setup:'zone'}});}catch(e){setError(e instanceof CustomerServiceError&&e.code==='not_found'?(ar?'يجب نشر تحديث الـBackend أولاً.':'Deploy the backend update first.'):(ar?'تعذر حفظ المزرعة. راجع البيانات وحاول مرة أخرى.':'Could not save the farm. Check the details and try again.'));}finally{setBusy(false);}};
  return <AccountPage title={ar?'إضافة مزرعة':'Add farm'}><Text style={[styles.step,{textAlign:isRTL?'right':'left'}]}>{ar?'الخطوة 1 من 3 · الأساسيات':'Step 1 of 3 · Essentials'}</Text><AccountField label={ar?'اسم المزرعة':'Farm name'} value={name} onChangeText={setName} placeholder={ar?'مثال: مزرعة العين':'Example: Al Ain Farm'}/><Text style={[ui.label,{textAlign:isRTL?'right':'left'}]}>{ar?'نوع الزراعة':'Growing type'}</Text><View style={[styles.options,{flexDirection:isRTL?'row-reverse':'row'}]}>{types.map(item=><Choice key={item.value} label={ar?item.ar:item.en} active={type===item.value} onPress={()=>setType(item.value)}/>)}</View><Text style={[styles.step,{textAlign:isRTL?'right':'left'}]}>{ar?'الخطوة 2 من 3 · الموقع':'Step 2 of 3 · Location'}</Text><AccountField label={ar?'الإمارة':'Emirate'} value={emirate} onChangeText={setEmirate} placeholder={ar?'اختياري':'Optional'}/><AccountField label={ar?'المنطقة':'Area or region'} value={region} onChangeText={setRegion} placeholder={ar?'اختياري':'Optional'}/><Notice text={ar?'لن نطلب إذن الموقع. يمكنك إضافة إحداثيات دقيقة لاحقاً عند اختيار «استخدام موقعي».':'Location permission is not requested. Precise coordinates can be added later only when you choose to use your location.'}/><Text style={[styles.step,{textAlign:isRTL?'right':'left'}]}>{ar?'الخطوة 3 من 3 · المساحة':'Step 3 of 3 · Area'}</Text><AccountField label={ar?'المساحة':'Area'} value={area} onChangeText={setArea} keyboardType="decimal-pad" ltr placeholder={ar?'اختياري':'Optional'}/><View style={[styles.options,{flexDirection:isRTL?'row-reverse':'row'}]}>{(['m2','hectare','acre'] as AreaUnit[]).map(value=><Choice key={value} label={value==='m2'?'m²':value} active={unit===value} onPress={()=>setUnit(value)}/>)}</View><AccountField label={ar?'ملاحظات':'Notes'} value={notes} onChangeText={setNotes} multiline placeholder={ar?'يمكن استكمال البيانات المتقدمة لاحقاً':'Advanced details can be completed later'}/>{error?<Notice error text={error}/>:null}<AppButton disabled={busy} label={busy?(ar?'جارٍ الحفظ...':'Saving...'):(ar?'حفظ والمتابعة':'Save and continue')} onPress={save}/></AccountPage>;
}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <MotionPressable accessibilityRole="radio" accessibilityState={{checked:active}} onPress={onPress} style={[styles.choice,active&&styles.active]}><Text style={[styles.choiceText,active&&styles.activeText]}>{label}</Text></MotionPressable>}
const styles=StyleSheet.create({step:{...typography.caption,color:colors.primary,marginTop:spacing.sm},options:{flexWrap:'wrap',gap:spacing.sm},choice:{minHeight:42,paddingHorizontal:spacing.md,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},active:{backgroundColor:colors.primary,borderColor:colors.primary},choiceText:{...typography.button,color:colors.text},activeText:{color:colors.surface}});
