import React, { useMemo, useState } from 'react';
import { Modal, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { AlertTriangle, CalendarDays, Check, ChevronLeft, ChevronRight, CloudOff, Droplets, FilePlus2, Leaf, ListTodo, MessageCircle, NotebookPen, Plus, Search, Sprout, Tractor, TriangleAlert, X } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppHeader } from '@/components/AppHeader';
import { AppButton } from '@/components/AppButton';
import { AppIconButton } from '@/components/AppIconButton';
import { EmptyState } from '@/components/ScreenState';
import { MotionPressable } from '@/components/Motion';
import { Fact, FarmRow, FarmSection, FarmSkeleton, StatusPill, farmUI } from '@/components/farm/FarmUI';
import { useAuth } from '@/contexts/AuthContext';
import { useFarm } from '@/contexts/FarmContext';
import { useLanguage } from '@/contexts/LanguageContext';
import { colors, radius, spacing, typography } from '@/constants/theme';
import type { FarmProblemStatus, FarmTask, FarmTaskStatus } from '@/types/farm';

const taskLabels:Record<FarmTaskStatus,{ar:string;en:string}>={scheduled:{ar:'مجدولة',en:'Scheduled'},due:{ar:'مستحقة',en:'Due'},completed:{ar:'مكتملة',en:'Completed'},missed:{ar:'متأخرة',en:'Overdue'},cancelled:{ar:'ملغاة',en:'Cancelled'}};
const problemLabels:Record<FarmProblemStatus,{ar:string;en:string}>={new:{ar:'جديدة',en:'New'},investigating:{ar:'قيد الفحص',en:'Investigating'},action_required:{ar:'تحتاج إجراء',en:'Action required'},monitoring:{ar:'تحت المتابعة',en:'Monitoring'},improving:{ar:'تتحسن',en:'Improving'},resolved:{ar:'تم حلها',en:'Resolved'},reopened:{ar:'عادت المشكلة',en:'Reopened'}};
const sameDay=(value:string)=>new Date(value).toDateString()===new Date().toDateString();

export default function MyFarmScreen(){
  const {user,ready}=useAuth(),{dashboard,loading,refreshing,error,cached,pendingCount,refresh,submit}=useFarm(),{language,isRTL}=useLanguage();
  const [actions,setActions]=useState(false),[busy,setBusy]=useState<string|null>(null),[notice,setNotice]=useState('');
  const ar=language==='ar',Arrow=isRTL?ChevronLeft:ChevronRight;
  const today=useMemo(()=>dashboard?.tasks.filter(task=>sameDay(task.dueAt)&&task.status!=='cancelled')??[],[dashboard]);
  const overdue=useMemo(()=>dashboard?.tasks.filter(task=>new Date(task.dueAt)<new Date()&&!sameDay(task.dueAt)&&!['completed','cancelled'].includes(task.status))??[],[dashboard]);
  const complete=async(task:FarmTask)=>{setBusy(task.id);setNotice('');try{const result=await submit('complete_task',{taskId:task.id});setNotice(result==='queued'?(ar?'تم حفظ الإجراء للمزامنة عند عودة الاتصال.':'Saved and will sync when connection returns.'):(ar?'تم تسجيل المهمة.':'Task completed.'));}catch{setNotice(ar?'تعذر تحديث المهمة. حاول مرة أخرى.':'Could not update the task. Try again.');}finally{setBusy(null);}};
  const date=(value:string)=>new Intl.DateTimeFormat(ar?'ar-AE':'en-AE',{hour:'numeric',minute:'2-digit'}).format(new Date(value));
  if(!ready||loading&&!dashboard)return <SafeAreaView style={farmUI.safe} edges={['top']}><AppHeader compact/><View style={farmUI.page}><FarmSkeleton/></View></SafeAreaView>;
  if(!user)return <SafeAreaView style={farmUI.safe} edges={['top']}><AppHeader compact/><View style={styles.gate}><View style={styles.gateIcon}><Sprout size={34} color={colors.primary}/></View><Text accessibilityRole="header" style={styles.gateTitle}>{ar?'احفظ بيانات مزرعتك وتابعها من أي جهاز':'Keep your farm records available on every device'}</Text><Text style={styles.gateBody}>{ar?'مزرعتي مساحة خاصة لإدارة المحاصيل والري والمهام والمشكلات. التسوق يظل متاحاً بدون تسجيل دخول.':'My Farm is your private space for crops, irrigation, tasks and problems. Shopping remains available without signing in.'}</Text><AppButton label={ar?'تسجيل الدخول':'Sign in'} onPress={()=>router.push('/auth/login')}/><AppButton secondary label={ar?'إنشاء حساب':'Create account'} onPress={()=>router.push('/auth/register')}/><AppButton secondary label={ar?'اسأل مهندس ميغ فارم':'Ask MIG FARM engineer'} onPress={()=>router.push('/(tabs)/assistant')}/><MotionPressable onPress={()=>router.replace('/(tabs)')}><Text style={styles.continue}>{ar?'متابعة التسوق':'Continue shopping'}</Text></MotionPressable></View></SafeAreaView>;
  const backendMissing=error==='not_found'||error==='database_not_configured';
  if(error&&!dashboard)return <SafeAreaView style={farmUI.safe} edges={['top']}><AppHeader compact/><EmptyState icon={CloudOff} title={backendMissing?(ar?'My Farm جاهزة وتحتاج نشر تحديث الـBackend':'My Farm is ready and needs the backend update deployed'):(ar?'تعذر تحميل مزرعتك':'Could not load your farm')} body={backendMissing?(ar?'بياناتك لن تُحفظ محلياً كبديل وهمي. انشر migration ومسارات API الجديدة أولاً.':'Your data will not be placed in a fake local backend. Deploy the new migration and API routes first.'):(ar?'تحقق من الاتصال ثم حاول مرة أخرى.':'Check your connection and try again.')} action={ar?'إعادة المحاولة':'Try again'} onAction={refresh}/></SafeAreaView>;
  if(!dashboard?.farms.length)return <SafeAreaView style={farmUI.safe} edges={['top']}><AppHeader compact/><EmptyState icon={Sprout} title={ar?'مزرعتك تبدأ من هنا':'Your farm starts here'} body={ar?'أضف مزرعتك ومحاصيلك علشان تتابع الري والمهام والمشاكل في مكان واحد.':'Add your farm and crops to manage irrigation, tasks and problems in one place.'} action={ar?'إضافة أول مزرعة':'Add your first farm'} onAction={()=>router.push('/my-farm/farm-form')}/></SafeAreaView>;
  return <SafeAreaView style={farmUI.safe} edges={['top']}><AppHeader compact/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={colors.primary}/>} contentContainerStyle={farmUI.page} showsVerticalScrollIndicator={false}>
    <View style={[styles.titleLine,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={{flex:1}}><Text style={[styles.eyebrow,{textAlign:isRTL?'right':'left'}]}>{ar?`صباح الخير، ${user.name.split(' ')[0]}`:`Good morning, ${user.name.split(' ')[0]}`}</Text><Text accessibilityRole="header" style={[farmUI.title,{textAlign:isRTL?'right':'left'}]}>{ar?'مزرعتي':'My Farm'}</Text></View><AppIconButton icon={Search} label={ar?'بحث في مزرعتي':'Search My Farm'} onPress={()=>router.push('/my-farm/search')}/><AppIconButton icon={CalendarDays} label={ar?'جدول مزرعتي':'Farm calendar'} onPress={()=>router.push('/my-farm/calendar')}/></View>
    {cached?<Text style={[farmUI.caption,{textAlign:isRTL?'right':'left'}]}>{ar?'تعرض بيانات محفوظة لحين اكتمال التحديث.':'Showing cached data while refreshing.'}</Text>:null}{pendingCount?<Text style={[farmUI.caption,{textAlign:isRTL?'right':'left'}]}>{ar?`${pendingCount} إجراء بانتظار المزامنة`:`${pendingCount} change${pendingCount===1?'':'s'} waiting to sync`}</Text>:null}{notice?<Text accessibilityLiveRegion="polite" style={[farmUI.caption,{color:colors.primary,textAlign:isRTL?'right':'left'}]}>{notice}</Text>:null}
    <View style={[styles.summary,{flexDirection:isRTL?'row-reverse':'row'}]}><Fact value={today.filter(x=>x.status!=='completed').length} label={ar?'مهام اليوم':'Tasks today'} icon={ListTodo}/><Fact value={overdue.length} label={ar?'متأخر':'Overdue'} icon={TriangleAlert}/><Fact value={dashboard.problems.length} label={ar?'مشكلات نشطة':'Active problems'} icon={AlertTriangle}/></View>
    <MotionPressable accessibilityRole="button" accessibilityLabel={ar?'اسأل مهندس ميغ فارم':'Ask MIG FARM engineer'} onPress={()=>router.push('/(tabs)/assistant')} style={[styles.assistantCta,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={styles.assistantIcon}><MessageCircle size={21} color={colors.surface}/></View><View style={{flex:1}}><Text style={[farmUI.label,{color:colors.surface,textAlign:isRTL?'right':'left'}]}>{ar?'اسأل مهندس ميغ فارم':'Ask MIG FARM engineer'}</Text><Text style={[farmUI.caption,{color:'#DCE9E0',textAlign:isRTL?'right':'left'}]}>{ar?'شارك المحصول أو المشكلة واحصل على خطوات واضحة':'Share a crop or problem and get clear next steps'}</Text></View><Arrow size={19} color={colors.surface}/></MotionPressable>
    {overdue.length?<FarmSection title={ar?'تحتاج انتباهك':'Needs your attention'}><View style={farmUI.card}>{overdue.slice(0,4).map(task=><TaskRow key={task.id} task={task} ar={ar} date={date} busy={busy===task.id} onComplete={()=>complete(task)}/>)}</View></FarmSection>:null}
    <FarmSection title={ar?'اليوم في مزرعتك':'Today on your farm'} action={ar?'الجدول':'Calendar'} onAction={()=>router.push('/my-farm/calendar')}><View style={farmUI.card}>{today.length?today.slice(0,6).map(task=><TaskRow key={task.id} task={task} ar={ar} date={date} busy={busy===task.id} onComplete={()=>complete(task)}/>):<Text style={[farmUI.body,{textAlign:isRTL?'right':'left'}]}>{ar?'لا توجد مهام مسجلة لليوم.':'No tasks recorded for today.'}</Text>}</View></FarmSection>
    <FarmSection title={ar?'مزارعي':'My farms'} action={ar?'إضافة':'Add'} onAction={()=>router.push('/my-farm/farm-form')}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{dashboard.farms.map(farm=><MotionPressable key={farm.id} accessibilityRole="button" accessibilityLabel={farm.name} onPress={()=>router.push({pathname:'/my-farm/[farmId]',params:{farmId:farm.id}})} style={styles.farmCard}><View style={[styles.farmTop,{flexDirection:isRTL?'row-reverse':'row'}]}><Tractor size={23} color={colors.primary}/><Arrow size={19} color={colors.muted}/></View><Text numberOfLines={1} style={[styles.farmName,{textAlign:isRTL?'right':'left'}]}>{farm.name}</Text><Text style={[farmUI.caption,{textAlign:isRTL?'right':'left'}]}>{ar?`${farm.activeCropCount||0} محاصيل نشطة`:`${farm.activeCropCount||0} active crops`}</Text><Text style={[farmUI.caption,{textAlign:isRTL?'right':'left'}]}>{ar?`${farm.activeProblemCount||0} مشكلات تحتاج متابعة`:`${farm.activeProblemCount||0} problems to follow up`}</Text></MotionPressable>)}</ScrollView></FarmSection>
    <FarmSection title={ar?'محاصيلي الآن':'Active crops'}>{dashboard.crops.length?<View style={farmUI.card}>{dashboard.crops.slice(0,5).map(crop=><FarmRow key={crop.id} icon={Leaf} title={crop.cropName} body={[crop.variety,crop.growthStage.replace('_',' ')].filter(Boolean).join(' · ')} onPress={()=>router.push({pathname:'/my-farm/crop/[id]',params:{id:crop.id}})}/>)}</View>:<Text style={farmUI.body}>{ar?'لا توجد محاصيل نشطة بعد.':'No active crops yet.'}</Text>}</FarmSection>
    {dashboard.problems.length?<FarmSection title={ar?'المشكلات النشطة':'Active problems'} action={ar?'عرض الكل':'View all'} onAction={()=>router.push('/my-farm/problems')}><View style={farmUI.card}>{dashboard.problems.slice(0,4).map(problem=><FarmRow key={problem.id} icon={AlertTriangle} title={problem.title} body={new Intl.DateTimeFormat(ar?'ar-AE':'en-AE',{day:'numeric',month:'short'}).format(new Date(problem.updatedAt))} trailing={<StatusPill status={problem.status} label={problemLabels[problem.status][ar?'ar':'en']}/>} onPress={()=>router.push({pathname:'/my-farm/problem/[id]',params:{id:problem.id}})}/>)}</View></FarmSection>:null}
    <FarmSection title={ar?'العمليات الأخيرة':'Recent operations'}>{dashboard.operations.length?<View style={farmUI.card}>{dashboard.operations.slice(0,5).map(op=><FarmRow key={op.id} icon={NotebookPen} title={op.productNameSnapshot||op.type.replace('_',' ')} body={new Intl.DateTimeFormat(ar?'ar-AE':'en-AE',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(op.performedAt))}/>)}</View>:<Text style={farmUI.body}>{ar?'لم تُسجل عمليات بعد.':'No operations recorded yet.'}</Text>}</FarmSection>
  </ScrollView><MotionPressable accessibilityRole="button" accessibilityLabel={ar?'إضافة سجل':'Add record'} onPress={()=>setActions(true)} style={styles.fab}><Plus size={26} color={colors.surface}/></MotionPressable>
  <Modal visible={actions} transparent animationType="fade" onRequestClose={()=>setActions(false)}><View style={styles.scrim}><SafeAreaView edges={['bottom']} style={styles.sheet}><View style={[styles.sheetTop,{flexDirection:isRTL?'row-reverse':'row'}]}><Text style={[styles.sheetTitle,{textAlign:isRTL?'right':'left'}]}>{ar?'تسجيل سريع':'Quick add'}</Text><AppIconButton icon={X} label={ar?'إغلاق':'Close'} onPress={()=>setActions(false)}/></View><View style={styles.actions}>{[{type:'irrigation',icon:Droplets,ar:'ري',en:'Irrigation'},{type:'operation',icon:NotebookPen,ar:'عملية زراعية',en:'Farm operation'},{type:'problem',icon:AlertTriangle,ar:'مشكلة',en:'Problem'},{type:'task',icon:ListTodo,ar:'مهمة',en:'Task'},{type:'harvest',icon:Sprout,ar:'حصاد',en:'Harvest'},{type:'note',icon:FilePlus2,ar:'ملاحظة',en:'Note'}].map(item=><MotionPressable key={item.type} onPress={()=>{setActions(false);router.push({pathname:'/my-farm/add',params:{type:item.type}})}} style={styles.actionItem}><item.icon size={23} color={colors.primary}/><Text style={farmUI.label}>{ar?item.ar:item.en}</Text></MotionPressable>)}</View></SafeAreaView></View></Modal>
  </SafeAreaView>;
}
function TaskRow({task,ar,date,busy,onComplete}:{task:FarmTask;ar:boolean;date:(v:string)=>string;busy:boolean;onComplete:()=>void}){const status:FarmTaskStatus=task.status==='scheduled'&&new Date(task.dueAt)<new Date()?'missed':task.status;return <FarmRow icon={task.type==='irrigation'?Droplets:ListTodo} title={task.title} body={date(task.dueAt)} trailing={task.status==='completed'?<StatusPill status="completed" label={taskLabels.completed[ar?'ar':'en']}/>:<MotionPressable disabled={busy} accessibilityRole="button" accessibilityLabel={ar?'تم':'Done'} onPress={onComplete} style={styles.done}><Check size={18} color={colors.surface}/></MotionPressable>}/>}
const styles=StyleSheet.create({
  gate:{flex:1,width:'100%',maxWidth:440,alignSelf:'center',justifyContent:'center',padding:spacing.xl,gap:spacing.md},gateIcon:{width:64,height:64,borderRadius:radius.md,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},gateTitle:{...typography.page,color:colors.text,textAlign:'center'},gateBody:{...typography.body,color:colors.muted,textAlign:'center',marginBottom:spacing.sm},continue:{...typography.button,color:colors.primary,textAlign:'center',padding:spacing.md},
  titleLine:{alignItems:'center',gap:spacing.sm},eyebrow:{...typography.caption,color:colors.primary,marginBottom:2},summary:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.sm,flexWrap:'wrap'},assistantCta:{minHeight:70,padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.primaryDark,alignItems:'center',gap:spacing.md},assistantIcon:{width:40,height:40,borderRadius:radius.md,backgroundColor:'rgba(255,255,255,0.12)',alignItems:'center',justifyContent:'center'},rail:{gap:spacing.md},farmCard:{width:224,minHeight:144,backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.lg,gap:spacing.xs},farmTop:{justifyContent:'space-between',marginBottom:spacing.sm},farmName:{...typography.section,color:colors.text},done:{width:36,height:36,borderRadius:radius.md,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},fab:{position:'absolute',right:20,bottom:20,width:56,height:56,borderRadius:28,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},scrim:{flex:1,backgroundColor:colors.overlay,justifyContent:'flex-end'},sheet:{width:'100%',maxWidth:680,alignSelf:'center',backgroundColor:colors.surface,padding:spacing.lg,gap:spacing.md},sheetTop:{alignItems:'center'},sheetTitle:{...typography.section,color:colors.text,flex:1},actions:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},actionItem:{width:'31%',minWidth:94,minHeight:88,backgroundColor:colors.surfaceMuted,borderRadius:radius.md,alignItems:'center',justifyContent:'center',gap:spacing.sm,padding:spacing.sm},
});
