import React, { useEffect, useState } from 'react';
import { Search as SearchIcon, Sprout } from 'lucide-react-native';
import { router } from 'expo-router';
import { AccountField, AccountPage, Notice } from '@/components/account/AccountUI';
import { FarmRow, FarmSection, FarmSkeleton, farmUI } from '@/components/farm/FarmUI';
import { useLanguage } from '@/contexts/LanguageContext';
import { farmService } from '@/services/farm';

type Item={id:string;farm_id?:string;farmId?:string;name?:string;crop_name?:string;title?:string;body?:string;type?:string;status?:string};
export default function FarmSearch(){const {language}=useLanguage(),ar=language==='ar';const [value,setValue]=useState(''),[results,setResults]=useState<Record<string,Item[]>>({}),[loading,setLoading]=useState(false),[error,setError]=useState('');useEffect(()=>{if(value.trim().length<2){setResults({});return;}const timer=setTimeout(()=>{setLoading(true);farmService.search(value.trim()).then(data=>{setResults(data as Record<string,Item[]>);setError('');}).catch(()=>setError(ar?'تعذر البحث.':'Search failed.')).finally(()=>setLoading(false));},250);return()=>clearTimeout(timer);},[value]);const groups=[['farms',ar?'المزارع':'Farms'],['zones',ar?'المناطق':'Zones'],['crops',ar?'المحاصيل':'Crops'],['problems',ar?'المشكلات':'Problems'],['operations',ar?'العمليات':'Operations'],['notes',ar?'الملاحظات':'Notes']];const open=(group:string,item:Item)=>{if(group==='farms')router.push({pathname:'/my-farm/[farmId]',params:{farmId:item.id}});else if(group==='crops')router.push({pathname:'/my-farm/crop/[id]',params:{id:item.id}});else if(group==='problems')router.push({pathname:'/my-farm/problem/[id]',params:{id:item.id}});else if(item.farm_id||item.farmId)router.push({pathname:'/my-farm/[farmId]',params:{farmId:item.farm_id||item.farmId||''}});};return <AccountPage title={ar?'البحث في مزرعتي':'Search My Farm'}><AccountField autoFocus label={ar?'ابحث في السجلات':'Search records'} value={value} onChangeText={setValue} placeholder={ar?'محصول، مشكلة، منطقة أو عملية':'Crop, problem, zone or operation'}/>{error?<Notice error text={error}/>:null}{loading?<FarmSkeleton/>:null}{!loading&&value.trim().length<2?<Notice text={ar?'اكتب حرفين على الأقل للبحث في بيانات مزرعتك الخاصة.':'Enter at least two characters to search your private farm data.'}/>:null}{!loading&&groups.map(([key,title])=>results[key]?.length?<FarmSection key={key} title={title}><>{results[key].map(item=><FarmRow key={item.id} icon={key==='problems'?SearchIcon:Sprout} title={item.name||item.crop_name||item.title||item.body||item.type||''} body={item.status||item.type} onPress={()=>open(key,item)}/>)}</></FarmSection>:null)}</AccountPage>}
