import { randomUUID } from 'node:crypto';
import { fail, pageResult, text, uuid } from '../lib/validation.mjs';

const FARM_TYPES = ['farm','greenhouse','home_garden','rooftop','project','other'];
const ZONE_TYPES = ['open_field','greenhouse','shade_house','garden','nursery','raised_bed','pots','other'];
const AREA_UNITS = ['m2','hectare','acre'];
const SOILS = ['sandy','clay','loam','mixed','unknown'];
const IRRIGATION = ['drip','sprinkler','manual','pivot','other'];
const WATER = ['network','well','tank','treated','other'];
const CROP_STATUS = ['planned','planted','active','harvesting','completed','stopped'];
const GROWTH = ['seedling','vegetative','flowering','fruit_set','production','harvest','finished'];
const TASK_TYPES = ['irrigation','fertilization','crop_inspection','pest_inspection','disease_inspection','planting','transplanting','pruning','training','treatment','maintenance','harvest','soil_test','water_test','problem_follow_up','custom'];
const TASK_STATUS = ['scheduled','due','completed','missed','cancelled'];
const PRIORITIES = ['normal','important','urgent'];
const OPERATION_TYPES = ['irrigation','fertilization','spraying','pruning','harvest','inspection','planting','maintenance','note','other'];
const PROBLEM_CATEGORIES = ['crop','soil','irrigation','water','pest','disease','nutrition','growth','equipment','other'];
const PROBLEM_STATUS = ['new','investigating','action_required','monitoring','improving','resolved','reopened'];
const SEVERITIES = ['mild','medium','severe'];
const FOLLOW_UP = ['better','same','worse','note'];

const enumValue = (value, allowed, fallback) => {
  const result = value ?? fallback;
  if (!allowed.includes(result)) throw fail(400, 'invalid_input');
  return result;
};
const optionalText = (value, max = 500) => value == null ? '' : text(value, max);
const optionalNumber = (value, { integer = false, max = 1e9 } = {}) => {
  if (value === undefined || value === null || value === '') return null;
  const result = Number(value);
  if (!Number.isFinite(result) || result < 0 || result > max || (integer && !Number.isInteger(result)))
    throw fail(400, 'invalid_input');
  return result;
};
const timestamp = (value, required = true) => {
  if (!value && !required) return null;
  const result = new Date(value);
  if (!value || Number.isNaN(result.getTime())) throw fail(400, 'invalid_input');
  return result.toISOString();
};
const dateOnly = (value, required = false) => {
  if (!value && !required) return null;
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(Date.parse(value + 'T00:00:00Z')))
    throw fail(400, 'invalid_input');
  return value;
};
const jsonObject = (value, fallback = null) => {
  if (value == null) return fallback;
  if (typeof value !== 'object' || Array.isArray(value)) throw fail(400, 'invalid_input');
  return value;
};
const area = (value, unit) => {
  const display = optionalNumber(value);
  if (display === null) return { display: null, unit: null, m2: null };
  const normalizedUnit = enumValue(unit, AREA_UNITS, 'm2');
  const factor = { m2: 1, hectare: 10000, acre: 4046.8564224 }[normalizedUnit];
  return { display, unit: normalizedUnit, m2: Number((display * factor).toFixed(3)) };
};
const iso = (value) => value ? new Date(value).toISOString() : null;
const numberOrNull = (value) => value == null ? null : Number(value);
const baseDTO = (row) => ({ id: row.id, version: row.version, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) });
const farmDTO = (r) => ({ ...baseDTO(r), name:r.name, type:r.type, emirate:r.emirate, region:r.region, area:numberOrNull(r.display_area), areaM2:numberOrNull(r.area_m2), areaUnit:r.area_unit, location:r.latitude==null?null:{ latitude:Number(r.latitude), longitude:Number(r.longitude) }, notes:r.notes, mainImage:r.main_image_url });
const zoneDTO = (r) => ({ ...baseDTO(r), farmId:r.farm_id, name:r.name, type:r.type, area:numberOrNull(r.display_area), areaM2:numberOrNull(r.area_m2), areaUnit:r.area_unit, soilType:r.soil_type, irrigationSystem:r.irrigation_system, waterSource:r.water_source, notes:r.notes });
const cropDTO = (r) => ({ ...baseDTO(r), farmId:r.farm_id, zoneId:r.zone_id, cropName:r.crop_name, cropId:r.crop_catalog_id, variety:r.variety, varietyId:r.variety_id, plantingDate:r.planting_date, transplantDate:r.transplant_date, expectedHarvestDate:r.expected_harvest_date, actualHarvestDate:r.actual_harvest_date, area:numberOrNull(r.display_area), areaM2:numberOrNull(r.area_m2), areaUnit:r.area_unit, plantCount:r.plant_count, growthStage:r.growth_stage, status:r.status, notes:r.notes });
const taskDTO = (r) => ({ ...baseDTO(r), userId:r.user_id, farmId:r.farm_id, zoneId:r.zone_id, cropCycleId:r.crop_cycle_id, problemId:r.problem_id, type:r.type, title:r.title, description:r.description, dueAt:iso(r.due_at), completedAt:iso(r.completed_at), completionNotes:r.completion_notes, actualMinutes:r.actual_minutes, result:r.result, status:r.status, priority:r.priority, recurrenceRule:r.recurrence_rule, source:r.source });
const irrigationDTO = (r) => ({ id:r.id, farmId:r.farm_id, zoneId:r.zone_id, cropCycleId:r.crop_cycle_id, startedAt:iso(r.started_at), durationMinutes:r.duration_minutes, waterVolumeLiters:numberOrNull(r.water_volume_liters), method:r.method, notes:r.notes, createdAt:iso(r.created_at), updatedAt:iso(r.updated_at) });
const operationDTO = (r) => ({ id:r.id, farmId:r.farm_id, zoneId:r.zone_id, cropCycleId:r.crop_cycle_id, type:r.type, performedAt:iso(r.performed_at), productId:numberOrNull(r.product_id), productNameSnapshot:r.product_name_snapshot, quantity:numberOrNull(r.quantity), unit:r.unit, applicationMethod:r.application_method, notes:r.notes, source:r.source, createdAt:iso(r.created_at) });
const problemDTO = (r) => ({ ...baseDTO(r), farmId:r.farm_id, zoneId:r.zone_id, cropCycleId:r.crop_cycle_id, category:r.category, title:r.title, description:r.description, severity:r.severity, status:r.status, firstObservedAt:iso(r.first_observed_at), lastFollowUpAt:iso(r.last_follow_up_at), resolvedAt:iso(r.resolved_at), suspectedCause:r.suspected_cause, verifiedCause:r.verified_cause, confirmedBy:r.confirmed_by, confirmedAt:iso(r.confirmed_at) });
const updateDTO = (r) => ({ id:r.id, problemId:r.problem_id, condition:r.condition, notes:r.notes, createdAt:iso(r.created_at) });
const harvestDTO = (r) => ({ id:r.id, farmId:r.farm_id, zoneId:r.zone_id, cropCycleId:r.crop_cycle_id, harvestedAt:iso(r.harvested_at), quantity:Number(r.quantity), unit:r.unit, customUnit:r.custom_unit, qualityNotes:r.quality_notes, createdAt:iso(r.created_at) });
const diagnosisDTO = (r) => ({ id:r.id,farmId:r.farm_id,zoneId:r.zone_id,cropCycleId:r.crop_cycle_id,problemId:r.problem_id,observations:r.observations,questions:r.questions,answers:r.answers,possibleCauses:r.possible_causes,recommendedInspections:r.recommended_inspections,verifiedDiagnosis:r.verified_diagnosis,confirmedBy:r.confirmed_by,confirmedAt:iso(r.confirmed_at),reviewStatus:r.review_status,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at) });

export function createFarmOS(db, { mediaStorage } = {}) {
  if (!db) {
    const unavailable = async () => { throw fail(503, 'database_not_configured'); };
    return new Proxy({}, { get: () => unavailable });
  }
  const one = async (sql, values) => (await db.query(sql, values)).rows[0];
  const ownedFarm = async (user, id) => {
    const row = await one('SELECT * FROM mig_farm.farms WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]);
    if (!row) throw fail(404,'not_found');
    return row;
  };
  const ownedZone = async (user, id, farmId) => {
    const values=[uuid(id),user.id], extra=farmId?' AND z.farm_id=$3':'';
    if(farmId) values.push(uuid(farmId));
    const row=await one(`SELECT z.* FROM mig_farm.farm_zones z JOIN mig_farm.farms f ON f.id=z.farm_id WHERE z.id=$1 AND f.user_id=$2 AND z.deleted_at IS NULL AND f.deleted_at IS NULL${extra}`,values);
    if(!row) throw fail(404,'not_found'); return row;
  };
  const ownedCrop = async (user,id,farmId) => {
    const values=[uuid(id),user.id], extra=farmId?' AND c.farm_id=$3':''; if(farmId) values.push(uuid(farmId));
    const row=await one(`SELECT c.* FROM mig_farm.crop_cycles c JOIN mig_farm.farms f ON f.id=c.farm_id WHERE c.id=$1 AND f.user_id=$2 AND c.deleted_at IS NULL AND f.deleted_at IS NULL${extra}`,values);
    if(!row) throw fail(404,'not_found'); return row;
  };
  const optionalLinks = async (user,{farmId,zoneId,cropCycleId}) => {
    const farm=await ownedFarm(user,farmId);
    if(zoneId) await ownedZone(user,zoneId,farm.id);
    if(cropCycleId) await ownedCrop(user,cropCycleId,farm.id);
    return farm;
  };
  return {
    async listFarms(user) {
      const rows=(await db.query(`SELECT f.*, (SELECT count(*)::int FROM mig_farm.farm_zones z WHERE z.farm_id=f.id AND z.deleted_at IS NULL) zone_count, (SELECT count(*)::int FROM mig_farm.crop_cycles c WHERE c.farm_id=f.id AND c.deleted_at IS NULL AND c.status IN ('planted','active','harvesting')) active_crop_count, (SELECT count(*)::int FROM mig_farm.farm_tasks t WHERE t.farm_id=f.id AND t.deleted_at IS NULL AND t.status<>'completed' AND t.due_at < date_trunc('day',now())+interval '1 day') due_task_count, (SELECT count(*)::int FROM mig_farm.farm_problems p WHERE p.farm_id=f.id AND p.deleted_at IS NULL AND p.status<>'resolved') active_problem_count FROM mig_farm.farms f WHERE f.user_id=$1 AND f.deleted_at IS NULL ORDER BY f.updated_at DESC,f.id`,[user.id])).rows;
      return rows.map(r=>({...farmDTO(r),zoneCount:r.zone_count,activeCropCount:r.active_crop_count,dueTaskCount:r.due_task_count,activeProblemCount:r.active_problem_count}));
    },
    async dashboard(user) {
      const farms=await this.listFarms(user);
      const tasks=(await db.query(`SELECT * FROM mig_farm.farm_tasks WHERE user_id=$1 AND deleted_at IS NULL AND status<>'cancelled' AND due_at < date_trunc('day',now())+interval '8 days' ORDER BY (completed_at IS NOT NULL),due_at,id LIMIT 60`,[user.id])).rows.map(taskDTO);
      const problems=(await db.query(`SELECT * FROM mig_farm.farm_problems WHERE user_id=$1 AND deleted_at IS NULL AND status<>'resolved' ORDER BY CASE severity WHEN 'severe' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,updated_at DESC LIMIT 20`,[user.id])).rows.map(problemDTO);
      const crops=(await db.query(`SELECT c.* FROM mig_farm.crop_cycles c JOIN mig_farm.farms f ON f.id=c.farm_id WHERE f.user_id=$1 AND f.deleted_at IS NULL AND c.deleted_at IS NULL AND c.status IN ('planted','active','harvesting') ORDER BY c.updated_at DESC LIMIT 20`,[user.id])).rows.map(cropDTO);
      const operations=(await db.query(`SELECT * FROM mig_farm.farm_operations WHERE user_id=$1 ORDER BY performed_at DESC,id LIMIT 12`,[user.id])).rows.map(operationDTO);
      return { farms, tasks, problems, crops, operations, weather:{ available:false, reason:'weather_provider_not_configured' }, generatedAt:new Date().toISOString() };
    },
    async createFarm(user,body) {
      const a=area(body.area,body.areaUnit), location=jsonObject(body.location);
      if(location && (!Number.isFinite(Number(location.latitude)) || !Number.isFinite(Number(location.longitude)))) throw fail(400,'invalid_input');
      const row=await one(`INSERT INTO mig_farm.farms(id,user_id,name,type,emirate,region,area_m2,display_area,area_unit,latitude,longitude,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[randomUUID(),user.id,text(body.name,120,true),enumValue(body.type,FARM_TYPES,'farm'),optionalText(body.emirate,60),optionalText(body.region,100),a.m2,a.display,a.unit,location?Number(location.latitude):null,location?Number(location.longitude):null,optionalText(body.notes,1000)]);
      return farmDTO(row);
    },
    async getFarm(user,id) { return farmDTO(await ownedFarm(user,id)); },
    async updateFarm(user,id,body) {
      const current=await ownedFarm(user,id), a=body.area===undefined?{m2:current.area_m2,display:current.display_area,unit:current.area_unit}:area(body.area,body.areaUnit), location=body.location===undefined?(current.latitude==null?null:{latitude:Number(current.latitude),longitude:Number(current.longitude)}):jsonObject(body.location);
      const row=await one(`UPDATE mig_farm.farms SET name=$1,type=$2,emirate=$3,region=$4,area_m2=$5,display_area=$6,area_unit=$7,latitude=$8,longitude=$9,notes=$10,version=version+1,updated_at=now() WHERE id=$11 AND user_id=$12 AND deleted_at IS NULL RETURNING *`,[body.name===undefined?current.name:text(body.name,120,true),enumValue(body.type,FARM_TYPES,current.type),body.emirate===undefined?current.emirate:optionalText(body.emirate,60),body.region===undefined?current.region:optionalText(body.region,100),a.m2,a.display,a.unit,location?Number(location.latitude):null,location?Number(location.longitude):null,body.notes===undefined?current.notes:optionalText(body.notes,1000),current.id,user.id]);
      return farmDTO(row);
    },
    async deleteFarm(user,id) { const farm=await ownedFarm(user,id); await db.query('UPDATE mig_farm.farms SET deleted_at=now(),updated_at=now(),version=version+1 WHERE id=$1 AND user_id=$2',[farm.id,user.id]); },
    async listZones(user,farmId) { const farm=await ownedFarm(user,farmId); return (await db.query('SELECT * FROM mig_farm.farm_zones WHERE farm_id=$1 AND deleted_at IS NULL ORDER BY created_at,id',[farm.id])).rows.map(zoneDTO); },
    async createZone(user,farmId,body) { const farm=await ownedFarm(user,farmId),a=area(body.area,body.areaUnit); const row=await one(`INSERT INTO mig_farm.farm_zones(id,farm_id,name,type,area_m2,display_area,area_unit,soil_type,irrigation_system,water_source,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[randomUUID(),farm.id,text(body.name,120,true),enumValue(body.type,ZONE_TYPES,'open_field'),a.m2,a.display,a.unit,body.soilType?enumValue(body.soilType,SOILS):null,body.irrigationSystem?enumValue(body.irrigationSystem,IRRIGATION):null,body.waterSource?enumValue(body.waterSource,WATER):null,optionalText(body.notes,1000)]); return zoneDTO(row); },
    async updateZone(user,id,body) { const c=await ownedZone(user,id),a=body.area===undefined?{m2:c.area_m2,display:c.display_area,unit:c.area_unit}:area(body.area,body.areaUnit); const row=await one(`UPDATE mig_farm.farm_zones SET name=$1,type=$2,area_m2=$3,display_area=$4,area_unit=$5,soil_type=$6,irrigation_system=$7,water_source=$8,notes=$9,version=version+1,updated_at=now() WHERE id=$10 RETURNING *`,[body.name===undefined?c.name:text(body.name,120,true),enumValue(body.type,ZONE_TYPES,c.type),a.m2,a.display,a.unit,body.soilType===undefined?c.soil_type:(body.soilType?enumValue(body.soilType,SOILS):null),body.irrigationSystem===undefined?c.irrigation_system:(body.irrigationSystem?enumValue(body.irrigationSystem,IRRIGATION):null),body.waterSource===undefined?c.water_source:(body.waterSource?enumValue(body.waterSource,WATER):null),body.notes===undefined?c.notes:optionalText(body.notes,1000),c.id]); return zoneDTO(row); },
    async deleteZone(user,id) { const z=await ownedZone(user,id); await db.query('UPDATE mig_farm.farm_zones SET deleted_at=now(),updated_at=now(),version=version+1 WHERE id=$1',[z.id]); },
    async listCrops(user,farmId) { const farm=await ownedFarm(user,farmId); return (await db.query('SELECT * FROM mig_farm.crop_cycles WHERE farm_id=$1 AND deleted_at IS NULL ORDER BY updated_at DESC,id',[farm.id])).rows.map(cropDTO); },
    async createCrop(user,body) { const farm=await optionalLinks(user,body),a=area(body.area,body.areaUnit); const row=await one(`INSERT INTO mig_farm.crop_cycles(id,farm_id,zone_id,crop_name,crop_catalog_id,variety,variety_id,planting_date,transplant_date,expected_harvest_date,area_m2,display_area,area_unit,plant_count,growth_stage,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[randomUUID(),farm.id,body.zoneId?uuid(body.zoneId):null,text(body.cropName,120,true),body.cropId?text(body.cropId,120):null,optionalText(body.variety,120),body.varietyId?text(body.varietyId,120):null,dateOnly(body.plantingDate),dateOnly(body.transplantDate),dateOnly(body.expectedHarvestDate),a.m2,a.display,a.unit,optionalNumber(body.plantCount,{integer:true,max:100000000}),enumValue(body.growthStage,GROWTH,'seedling'),enumValue(body.status,CROP_STATUS,'planned'),optionalText(body.notes,1000)]); return cropDTO(row); },
    async getCrop(user,id) { return cropDTO(await ownedCrop(user,id)); },
    async updateCrop(user,id,body) { const c=await ownedCrop(user,id); if(body.zoneId) await ownedZone(user,body.zoneId,c.farm_id); const a=body.area===undefined?{m2:c.area_m2,display:c.display_area,unit:c.area_unit}:area(body.area,body.areaUnit); const row=await one(`UPDATE mig_farm.crop_cycles SET zone_id=$1,crop_name=$2,variety=$3,planting_date=$4,transplant_date=$5,expected_harvest_date=$6,actual_harvest_date=$7,area_m2=$8,display_area=$9,area_unit=$10,plant_count=$11,growth_stage=$12,status=$13,notes=$14,version=version+1,updated_at=now() WHERE id=$15 RETURNING *`,[body.zoneId===undefined?c.zone_id:(body.zoneId?uuid(body.zoneId):null),body.cropName===undefined?c.crop_name:text(body.cropName,120,true),body.variety===undefined?c.variety:optionalText(body.variety,120),body.plantingDate===undefined?c.planting_date:dateOnly(body.plantingDate),body.transplantDate===undefined?c.transplant_date:dateOnly(body.transplantDate),body.expectedHarvestDate===undefined?c.expected_harvest_date:dateOnly(body.expectedHarvestDate),body.actualHarvestDate===undefined?c.actual_harvest_date:dateOnly(body.actualHarvestDate),a.m2,a.display,a.unit,body.plantCount===undefined?c.plant_count:optionalNumber(body.plantCount,{integer:true,max:100000000}),enumValue(body.growthStage,GROWTH,c.growth_stage),enumValue(body.status,CROP_STATUS,c.status),body.notes===undefined?c.notes:optionalText(body.notes,1000),c.id]); return cropDTO(row); },
    async completeCrop(user,id,body={}) { const c=await ownedCrop(user,id); const row=await one(`UPDATE mig_farm.crop_cycles SET status='completed',growth_stage='finished',actual_harvest_date=COALESCE($1,current_date),updated_at=now(),version=version+1 WHERE id=$2 RETURNING *`,[dateOnly(body.actualHarvestDate),c.id]); return cropDTO(row); },
    async listTasks(user,url) { const limit=Math.min(50,Math.max(1,Number(url.searchParams.get('limit')||30))),offset=Math.max(0,Number(url.searchParams.get('cursor')||0)); if(!Number.isInteger(limit)||!Number.isInteger(offset)) throw fail(400,'invalid_cursor'); const where=['user_id=$1','deleted_at IS NULL'],values=[user.id]; const add=(sql,v)=>{ values.push(v); where.push(sql.replace('?',`$${values.length}`)); }; if(url.searchParams.get('farmId')) add('farm_id=?',uuid(url.searchParams.get('farmId'))); if(url.searchParams.get('cropId')) add('crop_cycle_id=?',uuid(url.searchParams.get('cropId'))); const view=url.searchParams.get('view'); if(view==='today') where.push("due_at>=date_trunc('day',now()) AND due_at<date_trunc('day',now())+interval '1 day'"); else if(view==='upcoming') where.push("due_at>=now() AND status NOT IN ('completed','cancelled')"); else if(view==='overdue') where.push("due_at<now() AND status NOT IN ('completed','cancelled')"); else if(view && view!=='all') throw fail(400,'invalid_input'); values.push(limit+1,offset); const rows=(await db.query(`SELECT * FROM mig_farm.farm_tasks WHERE ${where.join(' AND ')} ORDER BY due_at,id LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows.map(taskDTO); return pageResult(rows,{offset,limit}); },
    async createTask(user,body) { const farm=await optionalLinks(user,body); if(body.problemId) { const p=await this.getProblem(user,body.problemId); if(p.farmId!==farm.id) throw fail(404,'not_found'); } const recurrence=jsonObject(body.recurrenceRule); if(recurrence && !['daily','interval_days','weekly','custom'].includes(recurrence.frequency)) throw fail(400,'invalid_input'); const row=await one(`INSERT INTO mig_farm.farm_tasks(id,user_id,farm_id,zone_id,crop_cycle_id,problem_id,type,title,description,due_at,status,priority,recurrence_rule,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[randomUUID(),user.id,farm.id,body.zoneId?uuid(body.zoneId):null,body.cropCycleId?uuid(body.cropCycleId):null,body.problemId?uuid(body.problemId):null,enumValue(body.type,TASK_TYPES,'custom'),text(body.title,180,true),optionalText(body.description,1000),timestamp(body.dueAt),enumValue(body.status,TASK_STATUS,'scheduled'),enumValue(body.priority,PRIORITIES,'normal'),recurrence,enumValue(body.source,['user','problem_follow_up','system'],'user')]); return taskDTO(row); },
    async updateTask(user,id,body) { const c=await one('SELECT * FROM mig_farm.farm_tasks WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]); if(!c) throw fail(404,'not_found'); const row=await one(`UPDATE mig_farm.farm_tasks SET type=$1,title=$2,description=$3,due_at=$4,status=$5,priority=$6,recurrence_rule=$7,version=version+1,updated_at=now() WHERE id=$8 AND user_id=$9 RETURNING *`,[enumValue(body.type,TASK_TYPES,c.type),body.title===undefined?c.title:text(body.title,180,true),body.description===undefined?c.description:optionalText(body.description,1000),body.dueAt===undefined?c.due_at:timestamp(body.dueAt),enumValue(body.status,TASK_STATUS,c.status),enumValue(body.priority,PRIORITIES,c.priority),body.recurrenceRule===undefined?c.recurrence_rule:jsonObject(body.recurrenceRule),c.id,user.id]); return taskDTO(row); },
    async completeTask(user,id,body={}) { const c=await one('SELECT * FROM mig_farm.farm_tasks WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]); if(!c) throw fail(404,'not_found'); return db.transaction(async client=>{ const row=(await client.query(`UPDATE mig_farm.farm_tasks SET status='completed',completed_at=$1,completion_notes=$2,actual_minutes=$3,result=$4,version=version+1,updated_at=now() WHERE id=$5 AND user_id=$6 RETURNING *`,[timestamp(body.actualTime||new Date().toISOString()),optionalText(body.notes,1000),optionalNumber(body.actualMinutes,{integer:true,max:10080}),optionalText(body.result,500),c.id,user.id])).rows[0]; if(c.recurrence_rule){ const next=nextDue(c.due_at,c.recurrence_rule); if(next) await client.query(`INSERT INTO mig_farm.farm_tasks(id,user_id,farm_id,zone_id,crop_cycle_id,problem_id,type,title,description,due_at,status,priority,recurrence_rule,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'scheduled',$11,$12,$13)`,[randomUUID(),user.id,c.farm_id,c.zone_id,c.crop_cycle_id,c.problem_id,c.type,c.title,c.description,next,c.priority,c.recurrence_rule,c.source]); } return taskDTO(row); }); },
    async deleteTask(user,id) { const result=await db.query('UPDATE mig_farm.farm_tasks SET deleted_at=now(),updated_at=now(),version=version+1 WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]); if(!result.rowCount) throw fail(404,'not_found'); },
    async listIrrigation(user,url) { const {where,values}=recordFilter(user,url); return (await db.query(`SELECT * FROM mig_farm.irrigation_records WHERE ${where} ORDER BY started_at DESC,id LIMIT 50`,values)).rows.map(irrigationDTO); },
    async createIrrigation(user,body) { const farm=await optionalLinks(user,body); if(!body.zoneId) throw fail(400,'invalid_input'); const row=await one(`INSERT INTO mig_farm.irrigation_records(id,user_id,farm_id,zone_id,crop_cycle_id,started_at,duration_minutes,water_volume_liters,method,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[randomUUID(),user.id,farm.id,uuid(body.zoneId),body.cropCycleId?uuid(body.cropCycleId):null,timestamp(body.startedAt||new Date().toISOString()),optionalNumber(body.durationMinutes,{integer:true,max:10080}),optionalNumber(body.waterVolumeLiters),enumValue(body.method,IRRIGATION),optionalText(body.notes,1000)]); return irrigationDTO(row); },
    async updateIrrigation(user,id,body) { const c=await one('SELECT * FROM mig_farm.irrigation_records WHERE id=$1 AND user_id=$2',[uuid(id),user.id]); if(!c) throw fail(404,'not_found'); const row=await one(`UPDATE mig_farm.irrigation_records SET started_at=$1,duration_minutes=$2,water_volume_liters=$3,method=$4,notes=$5,updated_at=now() WHERE id=$6 AND user_id=$7 RETURNING *`,[body.startedAt===undefined?c.started_at:timestamp(body.startedAt),body.durationMinutes===undefined?c.duration_minutes:optionalNumber(body.durationMinutes,{integer:true,max:10080}),body.waterVolumeLiters===undefined?c.water_volume_liters:optionalNumber(body.waterVolumeLiters),enumValue(body.method,IRRIGATION,c.method),body.notes===undefined?c.notes:optionalText(body.notes,1000),c.id,user.id]); return irrigationDTO(row); },
    async listOperations(user,url) { const {where,values}=recordFilter(user,url); return (await db.query(`SELECT * FROM mig_farm.farm_operations WHERE ${where} ORDER BY performed_at DESC,id LIMIT 50`,values)).rows.map(operationDTO); },
    async createOperation(user,body) { const farm=await optionalLinks(user,body); const row=await one(`INSERT INTO mig_farm.farm_operations(id,user_id,farm_id,zone_id,crop_cycle_id,type,performed_at,product_id,product_name_snapshot,quantity,unit,application_method,notes,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'user_recorded') RETURNING *`,[randomUUID(),user.id,farm.id,body.zoneId?uuid(body.zoneId):null,body.cropCycleId?uuid(body.cropCycleId):null,enumValue(body.type,OPERATION_TYPES,'other'),timestamp(body.performedAt||new Date().toISOString()),optionalNumber(body.productId,{integer:true}),body.productNameSnapshot?text(body.productNameSnapshot,180):null,optionalNumber(body.quantity),body.unit?text(body.unit,40):null,body.applicationMethod?text(body.applicationMethod,120):null,optionalText(body.notes,1000)]); return operationDTO(row); },
    async cropTimeline(user,id) { const crop=await ownedCrop(user,id); const operations=(await db.query('SELECT * FROM mig_farm.farm_operations WHERE user_id=$1 AND crop_cycle_id=$2 ORDER BY performed_at DESC,id',[user.id,crop.id])).rows.map(operationDTO).map(x=>({...x,eventType:'operation',eventAt:x.performedAt})); const irrigations=(await db.query('SELECT * FROM mig_farm.irrigation_records WHERE user_id=$1 AND crop_cycle_id=$2 ORDER BY started_at DESC,id',[user.id,crop.id])).rows.map(irrigationDTO).map(x=>({...x,eventType:'irrigation',eventAt:x.startedAt})); const problems=(await db.query('SELECT * FROM mig_farm.farm_problems WHERE user_id=$1 AND crop_cycle_id=$2 AND deleted_at IS NULL ORDER BY first_observed_at DESC,id',[user.id,crop.id])).rows.map(problemDTO).map(x=>({...x,eventType:'problem',eventAt:x.firstObservedAt})); const harvests=await this.listHarvests(user,id); return [{eventType:'crop_created',eventAt:crop.createdAt,crop},...operations,...irrigations,...problems,...harvests.map(x=>({...x,eventType:'harvest',eventAt:x.harvestedAt}))].sort((a,b)=>String(b.eventAt).localeCompare(String(a.eventAt))); },
    async listProblems(user,url) { const {where,values}=recordFilter(user,url); if(url.searchParams.get('status')) { values.push(enumValue(url.searchParams.get('status'),PROBLEM_STATUS)); } const status=url.searchParams.get('status')?` AND status=$${values.length}`:''; return (await db.query(`SELECT * FROM mig_farm.farm_problems WHERE ${where} AND deleted_at IS NULL${status} ORDER BY updated_at DESC,id LIMIT 50`,values)).rows.map(problemDTO); },
    async createProblem(user,body) { const farm=await optionalLinks(user,body); const row=await one(`INSERT INTO mig_farm.farm_problems(id,user_id,farm_id,zone_id,crop_cycle_id,category,title,description,severity,status,first_observed_at,suspected_cause) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[randomUUID(),user.id,farm.id,body.zoneId?uuid(body.zoneId):null,body.cropCycleId?uuid(body.cropCycleId):null,enumValue(body.category,PROBLEM_CATEGORIES,'crop'),text(body.title,180,true),optionalText(body.description,2000),enumValue(body.severity,SEVERITIES,'mild'),enumValue(body.status,PROBLEM_STATUS,'new'),timestamp(body.firstObservedAt||new Date().toISOString()),body.suspectedCause?text(body.suspectedCause,500):null]); return problemDTO(row); },
    async getProblem(user,id) { const row=await one('SELECT * FROM mig_farm.farm_problems WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]); if(!row) throw fail(404,'not_found'); return problemDTO(row); },
    async problemDetail(user,id) { const problem=await this.getProblem(user,id); const updates=(await db.query('SELECT * FROM mig_farm.farm_problem_updates WHERE problem_id=$1 AND user_id=$2 ORDER BY created_at DESC,id',[problem.id,user.id])).rows.map(updateDTO); const media=(await db.query('SELECT id,type,url,thumbnail_url,captured_at,notes,created_at FROM mig_farm.farm_media WHERE problem_id=$1 AND user_id=$2 ORDER BY captured_at DESC,id',[problem.id,user.id])).rows.map(r=>({id:r.id,type:r.type,url:r.url,thumbnailUrl:r.thumbnail_url,capturedAt:iso(r.captured_at),notes:r.notes,createdAt:iso(r.created_at)})); return {problem,updates,media}; },
    async updateProblem(user,id,body) { const c=await this.getProblem(user,id); const row=await one(`UPDATE mig_farm.farm_problems SET category=$1,title=$2,description=$3,severity=$4,status=$5,suspected_cause=$6,version=version+1,updated_at=now() WHERE id=$7 AND user_id=$8 RETURNING *`,[enumValue(body.category,PROBLEM_CATEGORIES,c.category),body.title===undefined?c.title:text(body.title,180,true),body.description===undefined?c.description:optionalText(body.description,2000),enumValue(body.severity,SEVERITIES,c.severity),enumValue(body.status,PROBLEM_STATUS,c.status),body.suspectedCause===undefined?c.suspectedCause:(body.suspectedCause?text(body.suspectedCause,500):null),c.id,user.id]); return problemDTO(row); },
    async followUp(user,id,body) { const problem=await this.getProblem(user,id),condition=enumValue(body.condition,FOLLOW_UP,'note'); return db.transaction(async client=>{ const update=(await client.query(`INSERT INTO mig_farm.farm_problem_updates(id,problem_id,user_id,condition,notes) VALUES($1,$2,$3,$4,$5) RETURNING *`,[randomUUID(),problem.id,user.id,condition,optionalText(body.notes,1000)])).rows[0]; const status=condition==='better'?'improving':condition==='worse'?'action_required':problem.status; const changed=(await client.query('UPDATE mig_farm.farm_problems SET status=$1,last_follow_up_at=now(),updated_at=now(),version=version+1 WHERE id=$2 AND user_id=$3 RETURNING *',[status,problem.id,user.id])).rows[0]; return {problem:problemDTO(changed),update:updateDTO(update)}; }); },
    async setProblemState(user,id,state,body={}) { const p=await this.getProblem(user,id),status=enumValue(state,PROBLEM_STATUS); if(!['resolved','reopened'].includes(status)) throw fail(400,'invalid_input'); return db.transaction(async client=>{ const row=(await client.query(`UPDATE mig_farm.farm_problems SET status=$1,resolved_at=$2,last_follow_up_at=now(),updated_at=now(),version=version+1 WHERE id=$3 AND user_id=$4 RETURNING *`,[status,status==='resolved'?new Date().toISOString():null,p.id,user.id])).rows[0]; await client.query('INSERT INTO mig_farm.farm_problem_updates(id,problem_id,user_id,condition,notes) VALUES($1,$2,$3,$4,$5)',[randomUUID(),p.id,user.id,status,optionalText(body.notes,1000)]); return problemDTO(row); }); },
    async uploadMedia(user,body) { await optionalLinks(user,body); if(!mediaStorage?.upload) throw fail(503,'farm_media_storage_not_configured'); return mediaStorage.upload(user,body); },
    async deleteMedia(user,id) { const media=await one('SELECT * FROM mig_farm.farm_media WHERE id=$1 AND user_id=$2',[uuid(id),user.id]); if(!media) throw fail(404,'not_found'); if(!mediaStorage?.remove) throw fail(503,'farm_media_storage_not_configured'); await mediaStorage.remove(media); await db.query('DELETE FROM mig_farm.farm_media WHERE id=$1 AND user_id=$2',[media.id,user.id]); },
    async createHarvest(user,body) { const crop=await ownedCrop(user,body.cropCycleId,body.farmId); if(body.zoneId) await ownedZone(user,body.zoneId,crop.farm_id); const unit=enumValue(body.unit,['kg','ton','box','piece','custom']); const custom=unit==='custom'?text(body.customUnit,40,true):null; const quantity=optionalNumber(body.quantity); if(quantity===null) throw fail(400,'invalid_input'); const row=await one(`INSERT INTO mig_farm.harvest_records(id,user_id,farm_id,zone_id,crop_cycle_id,harvested_at,quantity,unit,custom_unit,quality_notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[randomUUID(),user.id,crop.farm_id,body.zoneId?uuid(body.zoneId):crop.zone_id,crop.id,timestamp(body.harvestedAt||new Date().toISOString()),quantity,unit,custom,optionalText(body.qualityNotes,1000)]); return harvestDTO(row); },
    async listHarvests(user,cropId) { const crop=await ownedCrop(user,cropId); return (await db.query('SELECT * FROM mig_farm.harvest_records WHERE user_id=$1 AND crop_cycle_id=$2 ORDER BY harvested_at DESC,id',[user.id,crop.id])).rows.map(harvestDTO); },
    async createNote(user,body) { const farm=await optionalLinks(user,body); if(body.problemId) await this.getProblem(user,body.problemId); const row=await one(`INSERT INTO mig_farm.farm_notes(id,user_id,farm_id,zone_id,crop_cycle_id,problem_id,body) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[randomUUID(),user.id,farm.id,body.zoneId?uuid(body.zoneId):null,body.cropCycleId?uuid(body.cropCycleId):null,body.problemId?uuid(body.problemId):null,text(body.body,2000,true)]); return {id:row.id,farmId:row.farm_id,zoneId:row.zone_id,cropCycleId:row.crop_cycle_id,problemId:row.problem_id,body:row.body,createdAt:iso(row.created_at)}; },
    async listInventory(user,farmId) { const farm=await ownedFarm(user,farmId); return (await db.query('SELECT * FROM mig_farm.farm_inventory WHERE user_id=$1 AND farm_id=$2 AND deleted_at IS NULL ORDER BY updated_at DESC,id',[user.id,farm.id])).rows.map(r=>({id:r.id,farmId:r.farm_id,productId:numberOrNull(r.product_id),productNameSnapshot:r.product_name_snapshot,category:r.category,quantity:numberOrNull(r.quantity),unit:r.unit,notes:r.notes,createdAt:iso(r.created_at),updatedAt:iso(r.updated_at)})); },
    async createInventory(user,body) { const farm=await ownedFarm(user,body.farmId); const row=await one(`INSERT INTO mig_farm.farm_inventory(id,user_id,farm_id,product_id,product_name_snapshot,category,quantity,unit,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[randomUUID(),user.id,farm.id,optionalNumber(body.productId,{integer:true}),text(body.productNameSnapshot,180,true),text(body.category,80,true),optionalNumber(body.quantity),body.unit?text(body.unit,40):null,optionalText(body.notes,1000)]); return {id:row.id,farmId:row.farm_id,productId:numberOrNull(row.product_id),productNameSnapshot:row.product_name_snapshot,category:row.category,quantity:numberOrNull(row.quantity),unit:row.unit,notes:row.notes,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}; },
    async updateInventory(user,id,body) { const current=await one('SELECT * FROM mig_farm.farm_inventory WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]); if(!current)throw fail(404,'not_found'); const row=await one(`UPDATE mig_farm.farm_inventory SET product_name_snapshot=$1,category=$2,quantity=$3,unit=$4,notes=$5,updated_at=now() WHERE id=$6 AND user_id=$7 RETURNING *`,[body.productNameSnapshot===undefined?current.product_name_snapshot:text(body.productNameSnapshot,180,true),body.category===undefined?current.category:text(body.category,80,true),body.quantity===undefined?current.quantity:optionalNumber(body.quantity),body.unit===undefined?current.unit:(body.unit?text(body.unit,40):null),body.notes===undefined?current.notes:optionalText(body.notes,1000),current.id,user.id]); return {id:row.id,farmId:row.farm_id,productId:numberOrNull(row.product_id),productNameSnapshot:row.product_name_snapshot,category:row.category,quantity:numberOrNull(row.quantity),unit:row.unit,notes:row.notes,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at)}; },
    async deleteInventory(user,id) { const result=await db.query('UPDATE mig_farm.farm_inventory SET deleted_at=now(),updated_at=now() WHERE id=$1 AND user_id=$2 AND deleted_at IS NULL',[uuid(id),user.id]); if(!result.rowCount)throw fail(404,'not_found'); },
    async listAnalyses(user,farmId) { const farm=await ownedFarm(user,farmId); return (await db.query('SELECT * FROM mig_farm.soil_water_analyses WHERE user_id=$1 AND farm_id=$2 ORDER BY sampled_at DESC,id',[user.id,farm.id])).rows.map(r=>({id:r.id,farmId:r.farm_id,zoneId:r.zone_id,type:r.type,sampledAt:r.sampled_at,labName:r.lab_name,results:r.results,notes:r.notes,documentUrl:r.document_url,createdAt:iso(r.created_at)})); },
    async createAnalysis(user,body) { const farm=await optionalLinks(user,body); if(body.document)throw fail(503,'farm_media_storage_not_configured'); const results=jsonObject(body.results,{}),allowed=['pH','EC','salinity','organicMatter','N','P','K','Ca','Mg','Na','bicarbonate']; for(const [key,value] of Object.entries(results)){if(!allowed.includes(key)||!Number.isFinite(Number(value)))throw fail(400,'invalid_input');results[key]=Number(value);} const row=await one(`INSERT INTO mig_farm.soil_water_analyses(id,user_id,farm_id,zone_id,type,sampled_at,lab_name,results,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[randomUUID(),user.id,farm.id,body.zoneId?uuid(body.zoneId):null,enumValue(body.type,['soil','water']),dateOnly(body.sampledAt,true),body.labName?text(body.labName,180):null,results,optionalText(body.notes,1000)]); return {id:row.id,farmId:row.farm_id,zoneId:row.zone_id,type:row.type,sampledAt:row.sampled_at,labName:row.lab_name,results:row.results,notes:row.notes,documentUrl:null,createdAt:iso(row.created_at)}; },
    async listDiagnoses(user,problemId) { const problem=await this.getProblem(user,problemId); return (await db.query('SELECT * FROM mig_farm.diagnosis_sessions WHERE user_id=$1 AND problem_id=$2 ORDER BY created_at DESC,id',[user.id,problem.id])).rows.map(diagnosisDTO); },
    async createDiagnosis(user,body) { const farm=await optionalLinks(user,body); if(body.problemId){const problem=await this.getProblem(user,body.problemId);if(problem.farmId!==farm.id)throw fail(404,'not_found');} const arrays=['observations','questions','possibleCauses','recommendedInspections']; const values={}; for(const key of arrays){const list=body[key]??[];if(!Array.isArray(list)||list.length>50)throw fail(400,'invalid_input');values[key]=list.map(item=>text(item,500,true));} const answers=jsonObject(body.answers,{}); for(const [key,value] of Object.entries(answers)){if(typeof key!=='string'||key.length>120)throw fail(400,'invalid_input');answers[key]=text(value,1000);} const row=await one(`INSERT INTO mig_farm.diagnosis_sessions(id,user_id,farm_id,zone_id,crop_cycle_id,problem_id,observations,questions,answers,possible_causes,recommended_inspections) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[randomUUID(),user.id,farm.id,body.zoneId?uuid(body.zoneId):null,body.cropCycleId?uuid(body.cropCycleId):null,body.problemId?uuid(body.problemId):null,values.observations,values.questions,answers,values.possibleCauses,values.recommendedInspections]); return diagnosisDTO(row); },
    async search(user,query) { const q=text(query,120,true),like='%'+q.replace(/[%_\\]/g,'\\$&')+'%'; const [farms,zones,crops,problems,operations,notes]=await Promise.all([db.query(`SELECT id,name,type FROM mig_farm.farms WHERE user_id=$1 AND deleted_at IS NULL AND name ILIKE $2 ESCAPE '\\' LIMIT 10`,[user.id,like]),db.query(`SELECT z.id,z.farm_id,z.name,z.type FROM mig_farm.farm_zones z JOIN mig_farm.farms f ON f.id=z.farm_id WHERE f.user_id=$1 AND z.deleted_at IS NULL AND z.name ILIKE $2 ESCAPE '\\' LIMIT 10`,[user.id,like]),db.query(`SELECT c.id,c.farm_id,c.crop_name,c.variety,c.status FROM mig_farm.crop_cycles c JOIN mig_farm.farms f ON f.id=c.farm_id WHERE f.user_id=$1 AND c.deleted_at IS NULL AND (c.crop_name ILIKE $2 ESCAPE '\\' OR c.variety ILIKE $2 ESCAPE '\\') LIMIT 10`,[user.id,like]),db.query(`SELECT id,farm_id,title,category,status FROM mig_farm.farm_problems WHERE user_id=$1 AND deleted_at IS NULL AND (title ILIKE $2 ESCAPE '\\' OR description ILIKE $2 ESCAPE '\\') LIMIT 10`,[user.id,like]),db.query(`SELECT id,farm_id,type,performed_at,product_name_snapshot,notes FROM mig_farm.farm_operations WHERE user_id=$1 AND (notes ILIKE $2 ESCAPE '\\' OR product_name_snapshot ILIKE $2 ESCAPE '\\') LIMIT 10`,[user.id,like]),db.query(`SELECT id,farm_id,body,created_at FROM mig_farm.farm_notes WHERE user_id=$1 AND body ILIKE $2 ESCAPE '\\' LIMIT 10`,[user.id,like])]); return {farms:farms.rows,zones:zones.rows,crops:crops.rows,problems:problems.rows,operations:operations.rows,notes:notes.rows}; },
    async report(user,url) { const farm=await ownedFarm(user,url.searchParams.get('farmId')); const from=dateOnly(url.searchParams.get('from'),true),to=dateOnly(url.searchParams.get('to'),true); if(from>to) throw fail(400,'invalid_input'); const values=[user.id,farm.id,from,to]; const counts=await one(`SELECT (SELECT count(*)::int FROM mig_farm.crop_cycles WHERE farm_id=$2 AND deleted_at IS NULL) crops,(SELECT count(*)::int FROM mig_farm.farm_operations WHERE user_id=$1 AND farm_id=$2 AND performed_at::date BETWEEN $3 AND $4) operations,(SELECT count(*)::int FROM mig_farm.irrigation_records WHERE user_id=$1 AND farm_id=$2 AND started_at::date BETWEEN $3 AND $4) irrigations,(SELECT count(*)::int FROM mig_farm.farm_tasks WHERE user_id=$1 AND farm_id=$2 AND completed_at::date BETWEEN $3 AND $4) tasks_completed,(SELECT count(*)::int FROM mig_farm.farm_problem_updates u JOIN mig_farm.farm_problems p ON p.id=u.problem_id WHERE p.user_id=$1 AND p.farm_id=$2 AND u.condition='resolved' AND u.created_at::date BETWEEN $3 AND $4) problems_resolved`,values); const harvests=(await db.query(`SELECT unit,custom_unit,sum(quantity) quantity FROM mig_farm.harvest_records WHERE user_id=$1 AND farm_id=$2 AND harvested_at::date BETWEEN $3 AND $4 GROUP BY unit,custom_unit ORDER BY unit,custom_unit`,values)).rows.map(r=>({unit:r.unit,customUnit:r.custom_unit,quantity:Number(r.quantity)})); return {farm:farmDTO(farm),period:{from,to},facts:{crops:counts.crops,operations:counts.operations,irrigations:counts.irrigations,tasksCompleted:counts.tasks_completed,problemsResolved:counts.problems_resolved,harvests},labels:{records:'user_recorded_data',ai:'ai_observation',recommendations:'verified_recommendation',engineer:'human_engineer_review'}}; },
  };
}

function recordFilter(user,url) {
  const clauses=['user_id=$1'],values=[user.id];
  for(const [param,column] of [['farmId','farm_id'],['zoneId','zone_id'],['cropId','crop_cycle_id']]) if(url.searchParams.get(param)){ values.push(uuid(url.searchParams.get(param))); clauses.push(`${column}=$${values.length}`); }
  return {where:clauses.join(' AND '),values};
}
function nextDue(current,rule) {
  const next=new Date(current),frequency=rule?.frequency;
  if(frequency==='daily') next.setUTCDate(next.getUTCDate()+1);
  else if(frequency==='interval_days'){ const interval=Number(rule.interval); if(!Number.isInteger(interval)||interval<1||interval>365) return null; next.setUTCDate(next.getUTCDate()+interval); }
  else if(frequency==='weekly') next.setUTCDate(next.getUTCDate()+7);
  else return null;
  return next.toISOString();
}
